import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '../globals.css'
import { auth } from '@/auth'
import { SessionProvider } from 'next-auth/react'
import { LeftSidebar } from '@/components/shared/left-sidebar'
import { RightSidebar } from '@/components/shared/right-sidebar'
import { TopBar } from '@/components/shared/top-bar'

import { ReactQueryProvider } from '@/lib/providers'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'IBZN',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const session = await auth()
  return (
    <html lang="en">
      <body className={`${inter.className} overscroll-y-contain`}>
        <SessionProvider session={session}>
          <ReactQueryProvider>
            <TopBar />
            <main>
              <div className="relative w-screen flex">
                <LeftSidebar />
                <div className="w-full pt-12 px-20">{children}</div>
                <RightSidebar />
              </div>
            </main>
          </ReactQueryProvider>
        </SessionProvider>
      </body>
    </html>
  )
}
