import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '../globals.css'
import { Topbar } from '@/components/shared/topbar'
import { auth } from '@/auth'
import { SessionProvider } from 'next-auth/react'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'IBZN',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const session = await auth()
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider session={session}>
          <Topbar />
          {children}
        </SessionProvider>
      </body>
    </html>
  )
}
